version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 043503528386.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t 043503528386.dkr.ecr.us-east-1.amazonaws.com/todolist:latest .
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 043503528386.dkr.ecr.us-east-1.amazonaws.com/todolist:latest
      - echo Writing image definitions file...
      - printf '[{"name":"my-container","imageUri":"%s"}]' $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/043503528386.dkr.ecr.us-east-1.amazonaws.com/todolist:latest > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
